# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Collect conanfile deps

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag to create'
        required: true
        default: '1.0.0'

jobs:

  release:
    runs-on: ubuntu-latest
    env:
        build_dir: .
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build

    - name: Check conanfile.txt
      id: mipsdk_version_id
      run: |
        wget -O - https://github.com/conan-io/conan/releases/download/$CONAN_VERSION/conan-$CONAN_VERSION-linux-x86_64.tgz | tar xz -C $CONAN_INSTALL_DIR --strip-components 1
        cat conanfile.txt
      env:
        CONAN_INSTALL_DIR: /conan2
        CONAN_VERSION: 2.17.1

    - name: Create release without assets
      run: gh release create $REPO_TAG --notes "$RELEASE_NOTES" --title "$RELEASE_TITLE"
      env:
          REPO_TAG: ${{ github.event.inputs.tag }}
          RELEASE_NOTES: "Complete dependencies list from conanfile.txt: ${{ github.event.inputs.tag }}"
          RELEASE_TITLE: "Conanfile deps ${{ github.event.inputs.tag }}"
          GH_TOKEN: ${{ github.token }}

    - name: Upload assets to release
      run: gh release upload $REPO_TAG $build_dir/conanfile.txt --clobber
      env:
          REPO_TAG: ${{ github.event.inputs.tag }}
          GH_TOKEN: ${{ github.token }}