# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Collect conanfile deps

on:
  workflow_dispatch:
    inputs:
      conanfiletxt:
        description: 'conanfile.txt content'
        required: true
        default: '[requires]\nzlib/1.3.1'

jobs:

  release:
    runs-on: ubuntu-latest
    env:
        build_dir: .
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build

    - name: Check conanfile.txt
      id: mipsdk_version_id
      run: |
        echo "${{ github.event.inputs.conanfiletxt }}" >> conanfile.txt
        cat conanfile.txt

    - name: Create release without assets
      run: gh release create $REPO_TAG --notes "$RELEASE_NOTES" --title "$RELEASE_TITLE"
      env:
          REPO_TAG: conan1.0
          RELEASE_NOTES: "Complete dependencies list from conanfile.txt: ${{ github.event.inputs.conanfiletxt }}"
          RELEASE_TITLE: "conandeps 1.0"
          GH_TOKEN: ${{ github.token }}

    - name: Upload assets to release
      run: gh release upload $REPO_TAG $build_dir/conanfile.txt --clobber
      env:
          REPO_TAG: conan1.0
          GH_TOKEN: ${{ github.token }}